apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
data:
  LLM_PROVIDER: "local"
  EMBEDDING_PROVIDER: "huggingface"
  EMBEDDING_MODEL_NAME: "intfloat/multilingual-e5-base"
  GEMINI_LLM_MODEL: "gemini-2.0-flash-exp"
  API_BASE_URL: "http://rag-backend:8000"
  HF_CACHE_DIR: "/app/models_cache"
  VECTOR_STORE_PATH: "/app/data/vector_store"
  METRICS_HISTORY_DIR: "/app/metrics_history"
