apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-frontend-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: rag.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-frontend
                port:
                  number: 80
